### ISSUE TITLE
EcoMAX920 frames

### ISSUE THREAD

**Issue by svenlange2** [denpamusic/hassio-plum-ecomax#3]
I started a new issue here as its more suitably a new topic. As dont have RS485 wifi yet, so I tried with USB RS485 dongle to capture frames from the ecoNET port. Goal was to establish connection with the python - but this applies to the HASS as well. I did not get any devices with python. COM port connection was good as it seemed if I supplied wrong port it complained about connection. Devices array _len_() fuction gave me 0 devices and the example code did not produce any output. The frames which I capture are here below with new line added for every HEX value 69 which I presume is the start of frame. Maybe it helps.

Edit: recaptured at 115200 speed and it seems the frame start is 69
Edit #2: probably modbus lines are inverted. Ill post later correct frames

**Comment by denpamusic** [comment]
Thank you for your work!

Frame start should be 0x68 as you assumed before and frame end should be 0x16.
You can check out protocol bytemap here: https://github.com/denpamusic/PyPlumIO#protocol and in [ecomax.py](https://gist.github.com/denpamusic/6375c2a57716dc42861350f0eebc1e68#file-ecomax-py-L23) from official firmware.

Basically it should be: 0x68 + 2 bytes for frame length (unsigned short) + 1 byte recipient address + 1 byte sender address + 1 byte sender type + 1 byte ecoNET version + 1 byte command + (sometimes payload data) + 1 byte checksum + 0x16
AFIK your device is supposed to work with official ecoNET 300 module, so believe they use same protocol.

Serial setting in ecoNET firmware are defined as following:
- baudrate: 115200
- bytesize: 8
- parity: none
- stopbits: 1

**Comment by denpamusic** [comment]
I also think that this discussion should belong to PyPlumIO repo, since all low level stuff is done by the library.
If possible could you please open issue over there: https://github.com/denpamusic/PyPlumIO/issues.
