### ISSUE TITLE
Flame intensity on EcoMAX920

### ISSUE THREAD

**Issue by svenlange2** [denpamusic/hassio-plum-ecomax#5]
As the plumio library detects in my case variable "optical_temp" that is actually a 0-100% falme intensity sensor, I added to the python script sensors.py, line "EcomaxPercentSensor(connection, "optical_temp", "Flame Intensity")". This way I got the flame intencity value displayed in HASS. I suggest to add this permanently to the script at least in case of EcoMAX920.

**Comment by denpamusic** [comment]
Thank you very much for feedback!

I'll implement check for supported features when adding integration to hass in the near future. Sensors that was not found during this check, will still be added to hass but marked as `inactive`, just in case of an error.

**Comment by denpamusic** [comment]
Done. Added "Flame Intensity" sensor as well as implemented capabilities check on integration setup.
